#!/bin/bash
echo Mounting filesystems
mount -a
echo Loading xen-netfront
/sbin/depmod -a
/sbin/modprobe xen-netfront
echo Loading xen-pcifront
/sbin/modprobe xen-pcifront
echo XXX not loading bnx2
#/sbin/modprobe bnx2
echo Sending DHCP
/sbin/ifconfig eth0 up
/sbin/dhclient eth0
/sbin/ifconfig eth1 up
/sbin/dhclient eth1
/sbin/rsyslogd&
/sbin/ifconfig lo 127.0.0.1 netmask 255.0.0.0 up
echo Starting udevd
/sbin/udevd&
echo Starting NFS services
/sbin/rpc.statd -p 600 -o 601 &
/usr/sbin/rpc.idmapd &
/sbin/portmap &
echo Setting AIO limit
/sbin/sysctl -w fs.aio-max-nr=444416
echo Starting xcp-sm-fs
/usr/bin/xcp-sm-fs&
exec /bin/bash

